from setting import Setting
from protocols import aloha, slotted_aloha, csma, csma_cd
print('aloha')
x = aloha(Setting(host_num=3, total_time=100, packet_num=4, max_colision_wait_time=20, p_resend=0.3, packet_size=3, link_delay=1, seed=4), True)
print('success_rate: {}'.format(x[0]))
print('idle_rate: {}'.format(x[1]))
print('collision_rate: {}'.format(x[2]))
print('slotted_aloha')
x = slotted_aloha(Setting(host_num=3, total_time=100, packet_num=4, max_colision_wait_time=20, p_resend=0.3, packet_size=3, link_delay=1, seed=4), True)
print('success_rate: {}'.format(x[0]))
print('idle_rate: {}'.format(x[1]))
print('collision_rate: {}'.format(x[2]))
print('csma')
x = csma(Setting(host_num=3, total_time=100, packet_num=4, max_colision_wait_time=20, p_resend=0.3, packet_size=3, link_delay=1, seed=4), True)
print('success_rate: {}'.format(x[0]))
print('idle_rate: {}'.format(x[1]))
print('collision_rate: {}'.format(x[2]))
print('csma_cd')
x = csma_cd(Setting(host_num=3, total_time=100, packet_num=4, max_colision_wait_time=20, p_resend=0.3, packet_size=3, link_delay=1, seed=4), True)
print('success_rate: {}'.format(x[0]))
print('idle_rate: {}'.format(x[1]))
print('collision_rate: {}'.format(x[2]))